------- Hafsa ZIAN ------------

-------------> Exercice 1


In [2]:
import numpy as np


x=np.array([1,2])
w1 = np.array([[0.5, 0.5],
              [0 , 0.5]])
w2 = np.array([1, -1])
y = 1  


def activation(x):
    return 1 / (1 + np.exp(-x))

def derivative_activation(x):
    return activation(x) * (1 - activation(x))


def model(x,w1,w2):
    z=w1.dot(x)
    A=activation(z)
    T=w2.dot(A)
    return activation(T)



print(model(x,w1,w2))



0.5216154934076027


In [5]:
import numpy as np

x = np.array([1, 2])
y = 1  
w1 = np.array([[0.5, 0.5], [0, 0.5]])  
w2 = np.array([1, -1]) 
n = 0.1

def activation(x):
    return 1 / (1 + np.exp(-x))

def cost(y, y_hat):
    return 0.5 * (y - y_hat)**2

def derivative_activation(x):
    return activation(x) * (1 - activation(x))

def model(x, w1, w2):
    z = w1.dot(x)  
    A = activation(z)
    T = w2.dot(A)  
    return activation(T)

for i in range(1000):  
    z1 = w1.dot(x)
    A = activation(z1)
    T = w2.dot(A)
    y_hat = activation(T)  
    error = y - y_hat
    dL_dT = -error * derivative_activation(T)
    dL_dw2 = dL_dT * A
    dL_dA = dL_dT * w2 * derivative_activation(z1)
    dL_dw1 = np.outer(dL_dA, x)

    w2 = w2 - n * dL_dw2
    w1 = w1 - n * dL_dw1

    if i % 100 == 0:
        print(f' {i}, Cost: {cost(y, y_hat)}')

print(f" w1: \n{w1}")
print(f" w2: \n{w2}")


 0, Cost: 0.1144258680738257
 100, Cost: 0.02911695533953433
 200, Cost: 0.014692673842918346
 300, Cost: 0.009539814438142094
 400, Cost: 0.0069752542076677365
 500, Cost: 0.005459616420692453
 600, Cost: 0.004465353742693727
 700, Cost: 0.0037658369363327247
 800, Cost: 0.003248384796065451
 900, Cost: 0.002850917735420436
 w1: 
[[ 0.78048325  1.06096651]
 [-0.17694534  0.14610933]]
 w2: 
[2.65606488 0.09485502]


--------------> Exercice 2


1) Operator AND & OR 

In [12]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])  
y_or = np.array([0, 1, 1, 1])   

w1 = w2 = 0.5
b = -1
n = 0.5  

def calculate(X, Y, w1, w2, b, n, i=2):
    for j in range(i):
        for k in range(len(X)):
            x1, x2 = X[k]
            z = w1*x1 + w2*x2 + b 
            y_hat = sigmoid(z) 
            error = Y[k] - y_hat
            dL_dz = error * sigmoid_derivative(z)  
            w1 += n * dL_dz * x1
            w2 += n * dL_dz * x2
            b += n * dL_dz  

        cost = np.mean((Y - sigmoid(w1*X[:,0] + w2*X[:,1] + b))**2)
        print(f"j {j + 1} - weights: w1 = {w1:.4f}, w2 = {w2:.4f}, b = {b:.4f}")

    
    return w1, w2, b

print("AND operation:")
w1, w2, b = calculate(x, y_and, w1, w2, b, n)

print("\n OR operation:")
w1, w2, b = calculate(x, y_or, w1, w2, b, n)


AND operation:
j 1 - weights: w1 = 0.5263, w2 = 0.5246, b = -1.0435
j 2 - weights: w1 = 0.5529, w2 = 0.5496, b = -1.0847

 OR operation:
j 1 - weights: w1 = 0.6783, w2 = 0.6758, b = -0.9094
j 2 - weights: w1 = 0.7833, w2 = 0.7824, b = -0.7644


2). Change the learning rate to η = 0.05 



In [14]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])  
y_or = np.array([0, 1, 1, 1])  

w1 = w2 = 0.5
b = -1
n = 0.05  

def calculate(inputs, outputs, w1, w2, b, n, i=2):
    for j in range(i):
        for k in range(len(inputs)):
            x1, x2 = inputs[k]
            z = w1*x1 + w2*x2 + b  
            y_hat = sigmoid(z)  
            
            error = outputs[k] - y_hat
            dL_dz = error * sigmoid_derivative(z)  
        
            w1 += n * dL_dz * x1
            w2 += n * dL_dz * x2
            b += n * dL_dz  

        print(f"j {j + 1} -  weights: w1 = {w1:.4f}, w2 = {w2:.4f}, b = {b:.4f}")
    
    return w1, w2, b

print("AND operation with η = 0.05:")
w1, w2, b = calculate(x, y_and, w1, w2, b, n)

print("\nOR operation with η = 0.05:")
w1, w2, b = calculate(x, y_or, w1, w2, b, n)


AND operation with η = 0.05:
j 1 -  weights: w1 = 0.5019, w2 = 0.5019, b = -1.0052
j 2 -  weights: w1 = 0.5038, w2 = 0.5038, b = -1.0103

OR operation with η = 0.05:
j 1 -  weights: w1 = 0.5173, w2 = 0.5173, b = -0.9921
j 2 -  weights: w1 = 0.5306, w2 = 0.5306, b = -0.9742


3) NAND & NOR

In [16]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

y_nand = np.array([1, 1, 1, 0]) 
y_nor = np.array([1, 0, 0, 0])   

w1 = w2 = 0.5
b = -1
n = 0.5  

def calculate(inputs, outputs, w1, w2, b, n, i=2):
    for j in range(i):
        for k in range(len(inputs)):
            x1, x2 = inputs[k]
            z = w1*x1 + w2*x2 + b  
            y_hat = sigmoid(z)  
            error = outputs[k] - y_hat
            dL_dz = error * sigmoid_derivative(z)  
            w1 += n * dL_dz * x1
            w2 += n * dL_dz * x2
            b += n * dL_dz  
        print(f"J {j + 1} -  weights: w1 = {w1:.4f}, w2 = {w2:.4f}, b = {b:.4f}")
    
    return w1, w2, b

print("NAND operation with η = 0.5:")
w1, w2, b = calculate(x, y_nand, w1, w2, b, n)

print("\nNOR operation with η = 0.5:")
w1, w2, b = calculate(x, y_nor, w1, w2, b, n)


NAND operation with η = 0.5:
J 1 -  weights: w1 = 0.4999, w2 = 0.5010, b = -0.8559
J 2 -  weights: w1 = 0.4952, w2 = 0.4978, b = -0.7173

NOR operation with η = 0.5:
J 1 -  weights: w1 = 0.3736, w2 = 0.3740, b = -0.8225
J 2 -  weights: w1 = 0.2704, w2 = 0.2689, b = -0.9012


------------ NAND & NOR with with η = 0.05

In [15]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

y_nand = np.array([1, 1, 1, 0])  
y_nor = np.array([1, 0, 0, 0])   


w1 = w2 = 0.5
b = -1
n = 0.05  

def calculate(inputs, outputs, w1, w2, b, n, i=2):
    for j in range(i):
        for k in range(len(inputs)):
            x1, x2 = inputs[k]
            z = w1*x1 + w2*x2 + b  
            y_hat = sigmoid(z) 
            

            error = outputs[k] - y_hat
            dL_dz = error * sigmoid_derivative(z)  
            

            w1 += n * dL_dz * x1
            w2 += n * dL_dz * x2
            b += n * dL_dz  

        print(f"J {j + 1} -  weights: w1 = {w1:.4f}, w2 = {w2:.4f}, b = {b:.4f}")
    
    return w1, w2, b


print("NAND operation with η = 0.05:")
w1, w2, b = calculate(x, y_nand, w1, w2, b, n)


print("\nNOR operation with η = 0.05:")
w1, w2, b = calculate(x, y_nor, w1, w2, b, n)


NAND operation with η = 0.05:
J 1 -  weights: w1 = 0.5009, w2 = 0.5009, b = -0.9846
J 2 -  weights: w1 = 0.5018, w2 = 0.5018, b = -0.9692

NOR operation with η = 0.05:
J 1 -  weights: w1 = 0.4909, w2 = 0.4909, b = -0.9775
J 2 -  weights: w1 = 0.4802, w2 = 0.4802, b = -0.9855


4)Operator XOR

In [18]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))


x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  
y_xor = np.array([[0], [1], [1], [0]])  


w1 = np.random.randn(2, 2) 
w2 = np.random.randn(2, 1)  
b1 = np.random.randn(1, 2)  
b2 = np.random.randn(1, 1)  

n = 0.5  


def calculate(inputs, outputs, w1, w2, b1, b2, n, i=2):
    for j in range(i):
        z1 = np.dot(inputs, w1) + b1  
        a1 = sigmoid(z1)  
        z2 = np.dot(a1, w2) + b2  
        a2 = sigmoid(z2)  
        error = outputs - a2
        d_a2 = error * sigmoid_derivative(a2)  
        d_w2 = np.dot(a1.T, d_a2)  
        d_b2 = np.sum(d_a2, axis=0, keepdims=True)  
        d_a1 = np.dot(d_a2, w2.T) * sigmoid_derivative(a1) 
        d_w1 = np.dot(inputs.T, d_a1)
        d_b1 = np.sum(d_a1, axis=0, keepdims=True)
        w1 += n * d_w1
        w2 += n * d_w2
        b1 += n * d_b1
        b2 += n * d_b2

        print(f"j {j + 1} - weights: w1 = {w1}, w2 = {w2}, b1 = {b1}, b2 = {b2}")
    
    return w1, w2, b1, b2, a2

w1, w2, b1, b2, a2 = calculate(x, y_xor, w1, w2, b1, b2, n)

print("\nFinal predictions for XOR:")
print(a2)


j 1 - weights: w1 = [[ 0.97769445  0.19166976]
 [-0.32731117 -0.35341678]], w2 = [[ 2.44879509]
 [-0.78543518]], b1 = [[-0.29704486 -1.48040682]], b2 = [[1.08940113]]
j 2 - weights: w1 = [[ 0.9291601   0.2084822 ]
 [-0.37137414 -0.33797725]], w2 = [[ 2.36490985]
 [-0.81392441]], b1 = [[-0.39038861 -1.4486566 ]], b2 = [[0.92646891]]

Final predictions for XOR:
[[0.87949755]
 [0.86239188]
 [0.92726454]
 [0.91686645]]


II)AND, OR, NAND, NOR, and XOR with a hidden layer

In [19]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))


x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  
y_and = np.array([[0], [0], [0], [1]])  
y_or = np.array([[0], [1], [1], [1]])   
y_nand = np.array([[1], [1], [1], [0]])  
y_nor = np.array([[1], [0], [0], [0]])  
y_xor = np.array([[0], [1], [1], [0]])  

np.random.seed(42)
w1 = np.random.randn(2, 2)  
w2 = np.random.randn(2, 1) 
b1 = np.random.randn(1, 2)  
b2 = np.random.randn(1, 1)  


n = 0.5

def calculate(inputs, outputs, w1, w2, b1, b2, n, i=1000):
    for j in range(i):
        z1 = np.dot(inputs, w1) + b1  
        a1 = sigmoid(z1)  
        z2 = np.dot(a1, w2) + b2  
        a2 = sigmoid(z2)  
        error = outputs - a2
        loss = np.mean(np.square(error))  
        d_a2 = error * sigmoid_derivative(a2)  
        d_w2 = np.dot(a1.T, d_a2)  
        d_b2 = np.sum(d_a2, axis=0, keepdims=True) 
        
        d_a1 = np.dot(d_a2, w2.T) * sigmoid_derivative(a1)  
        d_w1 = np.dot(inputs.T, d_a1)  
        d_b1 = np.sum(d_a1, axis=0, keepdims=True) 

        w1 += n * d_w1
        w2 += n * d_w2
        b1 += n * d_b1
        b2 += n * d_b2

        if j % 100 == 0:
            print(f"j {j+1}, Loss: {loss:.4f}")

    return w1, w2, b1, b2, a2

print("AND operation:")
w1, w2, b1, b2, a2 = calculate(x, y_and, w1, w2, b1, b2, n)
print("\nFinal predictions for AND:")
print(a2)


print("\n OR operation:")
w1, w2, b1, b2, a2 = calculate(x, y_or, w1, w2, b1, b2, n)
print("\nFinal predictions for OR:")
print(a2)


print("\nNAND operation:")
w1, w2, b1, b2, a2 = calculate(x, y_nand, w1, w2, b1, b2, n)
print("\nFinal predictions for NAND:")
print(a2)


print("\n NOR operation:")
w1, w2, b1, b2, a2 = calculate(x, y_nor, w1, w2, b1, b2, n)
print("\nFinal predictions for NOR:")
print(a2)


print("\n XOR operation:")
w1, w2, b1, b2, a2 = calculate(x, y_xor, w1, w2, b1, b2, n)
print("\nFinal predictions for XOR:")
print(a2)


AND operation:
j 1, Loss: 0.1937
j 101, Loss: 0.1821
j 201, Loss: 0.1611
j 301, Loss: 0.1018
j 401, Loss: 0.1575
j 501, Loss: 0.1662
j 601, Loss: 0.1666
j 701, Loss: 0.1666
j 801, Loss: 0.1667
j 901, Loss: 0.1667

Final predictions for AND:
[[0.00323801]
 [0.33250548]
 [0.33250451]
 [0.33250571]]

 OR operation:
j 1, Loss: 0.3342
j 101, Loss: 0.0071
j 201, Loss: 0.0032
j 301, Loss: 0.0016
j 401, Loss: 0.0009
j 501, Loss: 0.0006
j 601, Loss: 0.0004
j 701, Loss: 0.0003
j 801, Loss: 0.0002
j 901, Loss: 0.0001

Final predictions for OR:
[[0.01697815]
 [0.99322347]
 [0.99322347]
 [0.99322347]]

NAND operation:
j 1, Loss: 0.4882
j 101, Loss: 0.3121
j 201, Loss: 0.2189
j 301, Loss: 0.1855
j 401, Loss: 0.1762
j 501, Loss: 0.1739
j 601, Loss: 0.1719
j 701, Loss: 0.1670
j 801, Loss: 0.1321
j 901, Loss: 0.1222

Final predictions for NAND:
[[0.99914381]
 [0.66547361]
 [0.6627835 ]
 [0.65069584]]

 NOR operation:
j 1, Loss: 0.3266
j 101, Loss: 0.0438
j 201, Loss: 0.0403
j 301, Loss: 0.0387
j 401, L